### ISSUE TITLE
Issue when loading localConfig in Env.fs

### ISSUE THREAD

**Issue by CallumVass** [Zaid-Ajaj/SAFE.Simplified#1]
Hi,

When I was trying to load a localConfig file I encountered an issue whereby it wasn't adding any key/value pairs. I've got a fix in my local branch so happy to do a PR (#2), I just wanted to make sure the way it is now isn't the intended behaviour?

https://github.com/Zaid-Ajaj/SAFE.Simplified/blob/098ce4bbb7908e20cc05f6084da9b3f476bd7aae/server/Env.fs#L64

https://github.com/Zaid-Ajaj/SAFE.Simplified/blob/098ce4bbb7908e20cc05f6084da9b3f476bd7aae/server/Env.fs#L77

**Comment by Zaid-Ajaj** [comment]
you are right, it should have been "if NOT contains key then ADD"
