### ISSUE TITLE
Invalid Hook Call. Hooks can only be called inside of the body of a function component.

### ISSUE THREAD

**Issue by aghoneim92** [Zaid-Ajaj/SAFE.Simplified#19]
I have upgraded React to 17.0.2 and Feliz to 1.40.1
When using React hooks, I get this error in my console and the app does not render. This is my code:
```f#
[<ReactComponent>]
let Component () =
  let state, setState = React.useState ""

  Html.h1 state


ReactDOM.render (Component(), document.getElementById "feliz-app")
```
It works with a project started with `dotnet new feliz -n AwesomeApp`. I'm guessing the difference is with the fable compiler version used. This template uses v2, while the Feliz-specific template uses v3.

This is the js output for the above f# code in the template:
```js
function Component() {
  var patternInput = Object(_fable_Feliz_1_40_1_React_fs__WEBPACK_IMPORTED_MODULE_0__["Feliz$002EReact$$React$002EuseState$002EStatic$$1505"])("");
  var state = patternInput[0];
  var setState = patternInput[1];
  return Object(_fable_Feliz_1_40_1_Interop_fs__WEBPACK_IMPORTED_MODULE_1__["Interop$$$reactElement"])("h1", {
    children: [state]
  });
}

Object(react_dom__WEBPACK_IMPORTED_MODULE_1__["render"])(Object(_App_fs__WEBPACK_IMPORTED_MODULE_0__["Component"])(), document.getElementById("feliz-app"));//# sourceURL=[module]

```

While the js output using the Feliz template is:
```js
function Component() {
  _s();

  var patternInput = Object(_fable_Feliz_1_40_1_React_fs_js__WEBPACK_IMPORTED_MODULE_0__["useFeliz_React__React_useState_Static_1505"])("");
  var state = patternInput[0];
  var setState = patternInput[1];
  return /*#__PURE__*/Object(react__WEBPACK_IMPORTED_MODULE_1__["createElement"])("h1", {
    children: [state]
  });
}

Object(react_dom__WEBPACK_IMPORTED_MODULE_2__["render"])( /*#__PURE__*/Object(react__WEBPACK_IMPORTED_MODULE_1__["createElement"])(Component, null), document.getElementById("feliz-app"));
```

My guess is that the problem is with the `createElement` call not being invoked in the first code sample.

**Comment by Zaid-Ajaj** [comment]
Hi @aghoneim92 indeed latest Feliz bits including the `[<ReactComponent>]` only works with Fable 3 (which allows for compiler plugins). In Fable 2 that this SAFE.Simplified template uses, you can use `React.functionComponent`:
```fs
// unit -> ReactElement
let Component = React.functionComponent(fun () ->
  let state, setState = React.useState ""
  Html.h1 state
)
```
Or you can use the new [SAFE.React](https://github.com/Zaid-Ajaj/SAFE.React) template that uses Fable 3 out of the box. I didn't have time to update this one to Fable 3 yet.

**Comment by aghoneim92** [comment]
Perfect! Thanks so much for the help
