### ISSUE TITLE
Just need you to contact me.

### ISSUE THREAD

**Issue by halcwb** [Zaid-Ajaj/SAFE.Simplified#3]
Hello Zaid, great work. Again!

But could you call me by cellphone, I would like to discuss some things would you.

Sorry for this intrusion, but I haven't got an alternative way to reach you. P.S. My phone is in my mail signature from work.

**Comment by Zaid-Ajaj** [comment]
Hello Casper, can you send me an email on my personal account at zaid.naom@gmail.com? Then I can send you my phone number as well :) 

> Sorry for this intrusion, but I haven't got an alternative way to reach you. P.S. My phone is in my mail signature from work. 

No worries, just send an email on the personal email above and I will contact you back!
