### ISSUE TITLE
How to generate-load-scripts

### ISSUE THREAD

**Issue by halcwb** [Zaid-Ajaj/SAFE.Simplified#5]
When using paket, you can use the `generate-load-scripts` option to generate script files that will load all dependencies. As the current framework relies on nuget directly, how can this be achieved without paket?

**Comment by Zaid-Ajaj** [comment]
Currently, there is no built-in support to generate this list and instead you have to manually create it from the paths of the packages that you are using. That said, probably it can be added easily as a FAKE build target to generate that load-scripts file. I will keep it in mind when I have a good time slot to get into it :wink:

**Comment by halcwb** [comment]
I recently switched to the official 'also quite simple' SAFE template because of the following reasons:

1. The aforementioned lack of support to easily create load scripts. 
2. Lack of paket support in general, which in the F# world is I think the package manager of choice.
3. The overall flexibility with the use of the SAFE stack template, for example, how to distribute.

So, for a non F# background starting template, I think the SAFE.Simplified is great. But for more advance complex apps I still would recommend the official SAFE template.

**Comment by Zaid-Ajaj** [comment]
That's great if you the official template works better for you. After all, this one is definitely not a one-size-fit-all type of template but I know many people like me would rather use this one instead
