### ISSUE TITLE
dotnet new template

### ISSUE THREAD

**Issue by JordanMarr** [Zaid-Ajaj/SAFE.Simplified#7]
I have mostly finished creating a dotnet new template for this.  
The default should leave it pretty much exactly the way you have it now, but it also allows for renaming the shared, server and client projects, project refs, build script strings, etc.  And it also allows adding an optional root namespace.
That may go against the idea of keeping it simple, so let me know if you are interested in this.

**Comment by Zaid-Ajaj** [comment]
Hi @JordanMarr, I am not a big fan of dotnet templates to be honest 😞 especially the maintenance part both from authors and from users. 

I understand that developers are used to "canonical" named namespaces but in my experience they just get in the way. I would rather keep this one as simple as it as now. Of course, there are compromises in how the template is structured but at the end of the day, this is just a template so people can change it to the way it suits them best.
